spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mebeli
    username: postgres
    password: Dosev562
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: "a-very-long-random-secret-string-at-least-256-bits-for-hs256-signing"
  expiration-ms: 14400000  # 4 hours